export const TOOL_REGISTRY = [
  'user.get_context',
  'conversation.get_active',
  'conversation.update_state',
  'catalog.search',
  'catalog.resolve',
  'client.search',
  'draft.create',
  'draft.set_client',
  'draft.add_item',
  'draft.remove_item',
  'draft.update_item',
  'draft.show',
  'draft.finish',
  'request.status',
  'request.approve',
  'request.reject',
  'pdf.generate_draft',
  'pdf.validate_signed',
  'report.generate',
  'allowlist.add',
  'allowlist.update',
  'allowlist.revoke',
  'audit.log'
] as const;
